services:
  whisperx:
    build:
      context: .
      dockerfile: Dockerfile
    image: emsi/whisperx
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - cache:/root/.cache
      - .:/whisperx

volumes:
  cache:
